name: docker
on: push  
  docker:
    runs-on: ubuntu-latest
    needs: download
    env:
      USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - name: login dockerhub
        uses: docker/login-action@v3
        with:
          username: $USERNAME
          password: $PASSWORD
      - name: checkout code
        uses: actions/checkout@v4
      - name: build docker image
        run: docker build -t $USERNAME/react_app .
      - name: push dockerhub
        run: docker push $USERNAME/react_app