name: Workflow lors d'un push
on: push
jobs:
  mon_job:
    runs-on: ubuntu-latest
    steps: 
      - name: Récupération de notre application
        uses: actions/checkout@v4

      - name: Mise en cache des dépendances
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-package-${{ hashFiles('**/package-lock.json') }}

      - name: Installation des dépendances
        run: npm install

      - name: build de l'application
        run: npm run build
      
      - name: test
        run: npm run test